FROM logstash:5.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

RUN logstash-plugin install logstash-filter-useragent
RUN logstash-plugin install logstash-filter-range
